### ISSUE TITLE
Metamask not interacting with melonport

### ISSUE THREAD

**Issue by AndrewGroom** [melonproject/ipfs-frontend#114]
I'm not a tech guy (I'm a musician) but my metamask isn't interactive with melonport at all. I have connected to the Kovan testnet and refreshed the page and still nothing shows. I've not had problems with using metamask before.

**Comment by henry-hayes** [comment]
I'm dealing with the same issue.  Also not an expert although (sometimes) good at following instructions...but I can't seem to get the Melonport to recognize that I've activated Metamask.

**Comment by schmidsi** [comment]
Hi guys. Thanks a lot for testing out Melon. Unfortunately, we are currently in the process of a big rewrite of the whole frontend. We'll post an update on our gitter/twitter in the next few days. Until then, please be patient a bit.

Closing this as a duplicate of #73
