### ISSUE TITLE
Disable actions that require running datafeed if datafeed is not running

### ISSUE THREAD

**Issue by perhamgirl** [melonproject/ipfs-frontend#128]
quantity = 1 is fine
price is greyed out to zero
total does not update and is not updating

after submitting request, receive this error
<img width="350" alt="screen shot 2018-01-04 at 15 02 29" src="https://user-images.githubusercontent.com/20302429/34569376-815dd4fc-f160-11e7-87d4-8fcc4cf096ce.png">

**Comment by schmidsi** [comment]
It is because DataFeed is not up. That said, I renamed the issue to clearly display this invalid state to the user.

Also, linked to #97
