### ISSUE TITLE
Reduce build size

### ISSUE THREAD

**Issue by ferranbt** [melonproject/ipfs-frontend#144]
When building with 'webpack' or 'react-scripts' the compiled main.js file is stored in ./public. That is the folder we eventually deploy on ipfs. However, since the folder also contains the semantic-ui configuration scripts, the total size of the directory end up being around 20MB which is hardly difficult to upload to ipfs.

**Comment by schmidsi** [comment]
I think we can move the semantic config files somewhere else. Actually, we don't use any JS from semantic because we use react-semantic-ui.

**Comment by ferranbt** [comment]
It seems that it is in use [here](https://github.com/melonproject/ipfs-frontend/blob/develop/package.json#L35)

**Comment by ferranbt** [comment]
React-semantic-ui does not inject the css. You still need to compile the css sources. Besides, it seems that to compile semantics-ui (npm run-script semantics:build) it requires to have gulp, gulp-help, require-dot-file, better-console... which is not installed right not on devDependencies.

I have not look too much into semantic-ui but you compile the code in the same directory where the sources are, so that you have to add a postprocess to move the files you want to /public.

The only possible workaround is to remove all the semantic-ui files and themes and just keep the compressed css file.

**Comment by schmidsi** [comment]
Actually, I like this workaround. Let's remove semantic-ui completely and just have another isolated repository for generating the customised css. What do you think?

**Comment by ferranbt** [comment]
From your comment here #150. If we are not planning to use semantic-ui anytime soon, I would remove all semantic-ui related elements and only keep the semantic.min.css file, even an unminimized (so we can change it) version if its possible. 

Inside /public, one folder called /static/css with all the styles, semantic.min.css and the inline css from react. Is there any plan to use styles in the react code as in #148? Note that I do not talk about the styles you inline in the react components. I think we eventually will migrate into the inline components and we can avoid things like #148 since we can have those files in the static css folder and we reduce the build complexity.

**Comment by schmidsi** [comment]
The plan is to move to something like [JSS](http://cssinjs.org/react-jss/?v=v8.2.1). Totally agree. We just need to have the semantic.min.css file around. Everything else can be removed.

Better to keep the semantic.min.css file and a separate "overwrites" or something so that we can recreate the semantic.min.css file at any time with an external semantic-ui config/installation if needed. But I hope we can avoid it until a JSS solution.

**Comment by schmidsi** [comment]
Until then, I recommend writing react-inline-styles. I.e.:
```javascript
<MyComp style={{ backgroundColor: "#badass" }} />
```
