### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by ferranbt** [melonproject/ipfs-frontend#145]
I have been navigating for around 2 minutes on the frontend. Just load the ranking, load the first fund, go back to the ranking and load another fund. This is the heap memory allocation of my Chrome browser.

![heap allocation](https://user-images.githubusercontent.com/30872539/34676421-064e2d04-f48d-11e7-95f1-29624ff27231.png)

It shows 75 MB of data allocated.

**Comment by jennazenk** [comment]
dom listeners?

**Comment by schmidsi** [comment]
I think this comes from the current implementation of ranking: To get the ranking without the the rankingContract, we make 3-4 request per fund --> for 300 funds more than 1000 requests. That bloats memory a lot! So I put this on hold until #151 is resolved.

**Comment by schmidsi** [comment]
I close this issue since it seems that it should've been resolved through the centralized ranking microservice.
