### ISSUE TITLE
Mixing styles

### ISSUE THREAD

**Issue by ferranbt** [melonproject/ipfs-frontend#148]
Related to #144. The frontend uses styles with semantic-ui compiled with gulp (we actually compiled them months ago and we use the compiled version since then) and then [this](https://github.com/melonproject/ipfs-frontend/blob/develop/src/index.css) 'inline' css style that has to be compiled. That increases the difficulty to compile the code on production.

**Comment by ferranbt** [comment]
That css file could go into a file in public folder

**Comment by schmidsi** [comment]
This are hacky overwrites. Move it where ever it's better for the build (maybe even inline into the main html).
