### ISSUE TITLE
Semantic-ui problems

### ISSUE THREAD

**Issue by ferranbt** [melonproject/ipfs-frontend#150]
The current [index](https://github.com/melonproject/ipfs-frontend/blob/develop/public/index.html) page, includes the semantic-ui css 'public/semantic/dist/semantic.min.css'. In gitignore, the path semantic/dist is not commited, so that with a complete clean installation there will be no styles. 

You may have the styles available shown on the screen because the content of semantic/dist is never removed unless you manually remove the ipfs-frontend folder, this is, stays the same between checkouts and pulls.

There is an old version of the styles under 'public/static/semantic.min.css'. I have been unable with the current installation to run again the gulp builds for semantic-ui.

**Comment by jennazenk** [comment]
added files here https://github.com/melonproject/ipfs-frontend/pull/147/commits/f180e51a5b0fdffcb4985bb0ab00b3511a854d1d

**Comment by schmidsi** [comment]
We don't need the semantic js files. Acutally, it is a problem that the semantic-ui build doesn't work anymore. But I do not want to invest much time in it since we should move to another styling solution soon.
