### ISSUE TITLE
Option to go back to /account if user wants to reset his account, delete his account or import other account

### ISSUE THREAD

**Issue by jennazenk** [melonproject/ipfs-frontend#153]

**Comment by schmidsi** [comment]
Maybe by clicking on the account hash in the sticky helper

**Comment by jennazenk** [comment]
Yes it's true but I also like the fact that the account hash redirects to etherscan. What do you think?

**Comment by schmidsi** [comment]
This was just the easiest thing to do. More elaborated would be:
- Click on address goes to a separate account page with options to create a new one and other goodies like etherscan links.

**Comment by jennazenk** [comment]
yep thats exactly what I'm doing now as we speak 👍
