### ISSUE TITLE
Not able to shut down melon fund

### ISSUE THREAD

**Issue by ddkothar** [melonproject/ipfs-frontend#161]
![fund shut down](https://user-images.githubusercontent.com/20861407/34782093-a67efe70-f5f5-11e7-9892-4d69e2de4da0.PNG)

-- Getting transaction error "r.owner is not a function", when trying to irreversibly shut down fund the melon fund.

**Comment by schmidsi** [comment]
Good catch. Thanks. Will be fixed in next deployment.
