### ISSUE TITLE
Not able to invest more in fund.

### ISSUE THREAD

**Issue by ddkothar** [melonproject/ipfs-frontend#164]
![image](https://user-images.githubusercontent.com/20861407/34787803-925c8636-f606-11e7-8322-eddf37e78e20.png)
 
I have tried more than 4, 5 time. but not getting any more fund.

**Comment by jennazenk** [comment]
thanks @ddkothar for reporting! Indeed there is a bug in the deployed version. Fix will be included in next deployment!
