### ISSUE TITLE
Melon.fund not loading for me

### ISSUE THREAD

**Issue by proehlen** [melonproject/ipfs-frontend#172]
On Chrome (Windows 10, Chrome Version 63.0.3239.132) I just get the spinning loading indicator:
![image](https://user-images.githubusercontent.com/8384068/35029347-270f1ed4-fb8d-11e7-9554-656f4bef2021.png)

On Firefox version 38.0.1 I just get a nearly blank page:
![image](https://user-images.githubusercontent.com/8384068/35029377-4869b008-fb8d-11e7-9ed9-5e36587b44cc.png)

**Comment by proehlen** [comment]
Sorry never mind, just took a very long time to load.

**Comment by schmidsi** [comment]
@proehlen Thanks for writing. Because we use the blockchain as a backend in a truly decentralised manner, performance is not as snappy as centralised services. That said, we are already working on some improvements, especially here on the ranking page. Stay tuned :D
