### ISSUE TITLE
Some links redirect to ipfs.io ; logo should redirect to melonport.com

### ISSUE THREAD

**Issue by jennazenk** [melonproject/ipfs-frontend#173]

**Comment by jennazenk** [comment]
-  "click here to go back to your fund's page." (on My Account section)
- Melon logo

**Comment by schmidsi** [comment]
The problem are links to "/" without the special <Link> and route action.

**Comment by jennazenk** [comment]
Fixed in 0.6! Should be fine now. If anyone sees any link like this pls reopen
