### ISSUE TITLE
Change quantity in form produces an error

### ISSUE THREAD

**Issue by ferranbt** [melonproject/ipfs-frontend#174]
I have created a fund and requested melon and ether from the faucet. After that, I have invested 40% on ICN. Then, I tried to invest on REP but whenever I try to change the quantity in the form It gives me this error and the page disappears, only the header stays.

![image](https://user-images.githubusercontent.com/30872539/35154695-79834150-fd2b-11e7-8052-1502bec01153.png)

**Comment by schmidsi** [comment]
I can reproduce it. It even throws with BTC-T. Investigate now.

**Comment by schmidsi** [comment]
Also mentioned here: #174
