### ISSUE TITLE
Faucet UI fails to update 'ETH' value

### ISSUE THREAD

**Issue by MeoMix** [melonproject/ipfs-frontend#175]
Heya,

I am playing around with Melon for the first time. I went to use the faucet. It worked appropriately, but I noted that the value of "ETH" displayed on the page did not update. The value of "MLN" did update. The value of "ETH" updated when I interacted with the page.

Here is a screenshot of the state of my page after successfully issuing a second request to the faucet. Note that "ETH" has not updated, but "MLN" has updated.

![image](https://user-images.githubusercontent.com/1380995/35201444-6126fa74-fed0-11e7-82fa-a2b9131520c0.png)

**Comment by ferranbt** [comment]
Hi there! This problem is being tackled on another issue on the faucet [repo](https://github.com/melonproject/faucet/issues/10). I'll close this in favor or the other one.
