### ISSUE TITLE
v0.6.0 feedback from John Orthwein/ Hansjoerg Hettich

### ISSUE THREAD

**Issue by perhamgirl** [melonproject/ipfs-frontend#177]
(copy pasted from an email)

Participation: Change the term “participation” to “Subscription” (and use “Redemptions” for redemptions).

On the Participation tab, add currency (MLN) as initially we were unsure, if we subscribe for MLN or for shares. Always define the fields.

Holdings: Would be great to add a tick box that allows to filter for actual holdings, removing all 0 holdings tokens. Also a filter by A-Z and/or allocation would be very useful / user friendly.

Trade: create a tab where one can see his trade history, naming it “Trade Confirmation” – ultimately a link to Etherscan (Kovan) for each trade, but maybe with a nicer interface

You added the Twitter functionality, which Jenna already used today - I think it’s very attractive and could be used by a lot of social-media-active people. Her tweet today already received some quality comments.

**Comment by jennazenk** [comment]
Thanks Mona for reporting! Very valuable feedback

**Comment by jennazenk** [comment]
Created separate issues to address this feedback : #186 #185 #184
