### ISSUE TITLE
Add Google Analytics 

### ISSUE THREAD

**Issue by jennazenk** [melonproject/ipfs-frontend#182]

**Comment by schmidsi** [comment]
We shouldn't track all users by default. Ask them on their first visit if they allow us to track or not and save this decision in a cookie/localstorage & option to disable tracking later -> Linked to #69

**Comment by jennazenk** [comment]
Agree

**Comment by retotrinkler** [comment]
would rather have it as a _default_; think google analytics isn't that big of a data collection issue.

eventually would like to have a vpn/tor version of it for privacy reasons eg in a settings menu. where users can also select to opt out of goolge analytics etc

**Comment by retotrinkler** [comment]
we can keep same settings as u mentioned in #69 

> If do not track browser flag is set: Don't send them by default
If not, send them by default but give the user a possibility to turn them off
