### ISSUE TITLE
Service worker is 404ing

### ISSUE THREAD

**Issue by MeoMix** [melonproject/ipfs-frontend#191]
Description:

I attempt to load my Melon fund at https://ipfs.io/ipns/melon.fund/. The page does not load except for some basic UI elements at the top. No error is displayed on the page.

I open developer console. I see errors. 
![image](https://user-images.githubusercontent.com/1380995/35453203-3590e94a-027e-11e8-8b07-a9d7d3b6dcdd.png)

Expected:

Melon fund should load. If an error is encountered then it should be communicated to the end user.

**Comment by schmidsi** [comment]
Hmm, I saw this before but it went away. What OS/Browser combination do you use?

**Comment by MeoMix** [comment]
![image](https://user-images.githubusercontent.com/1380995/35453592-a8ce77be-027f-11e8-9724-a93a5efe422f.png)

Slightly out of date. Updating now and giving it another shot. Everything was running smoothly last night before I went to bed and I haven't closed my browser or shutdown my PC. Definitely a bit odd.

**Comment by MeoMix** [comment]
After updating to 64.0.3282.119 and fully restarting the browser the page loaded successfully, but not without errors in the developer console.

![image](https://user-images.githubusercontent.com/1380995/35453787-549f39de-0280-11e8-86b3-f797f6fb5b50.png)

**Comment by MeoMix** [comment]
My best guess is that when you transitioned away from Infura some timing/connection logic started misbehaving. I feel like the service worker is trying to load information from a node with which a connection has yet to be established. Perhaps Infura was responding more quickly, and so a race condition wasn't occurring, but now is?

**Comment by schmidsi** [comment]
Yep, we have some issues with our own nodes right now but already some possible solutions. Thanks for reporting!

**Comment by MeoMix** [comment]
Sounds good! I'll leave you to it. Going to try to put together some UI feedback today!

**Comment by ferranbt** [comment]
I think that the service worker issue is related with the ipfs deployment and the deprecation warning is because of the library 'react-cntdwn' which uses 'moment-js' which has problems to find 'locate' libraries when compiled with webpack (used by react-scripts)

**Comment by MeoMix** [comment]
Why is removing the service worker the solution to this issue? The description of 38b8dbcdd565f4ca0853c5dfd28b3450b98ec8c7 only describes what has occurred (I can see that from the code changes) and not why it occurred.

**Comment by schmidsi** [comment]
The service worker implementation that comes bundled with create-react-app does not work with IPFS. Furthermore, since we are not delivering images, the expected caching mechanism doesn't help us. So better to remove unused code that throws errors.

**Comment by MeoMix** [comment]
Thanks for the explanation! Closing issue.
