### ISSUE TITLE
Metamask not working with Melon.Fund frontend

### ISSUE THREAD

**Issue by kingjacob** [melonproject/ipfs-frontend#198]
With the recent 0.6 update do you have to restore from mneumonic every time or is this a bug?

<img width="807" alt="screen shot 2018-01-29 at 9 34 43 pm" src="https://user-images.githubusercontent.com/806312/35549869-836113be-053c-11e8-8dc8-7a5117c8f8b2.png">

**Comment by schmidsi** [comment]
Hi @kingjacob, we do not use MetaMask anymore. The whole key management happens in-browser.

**Comment by kingjacob** [comment]
Ahh, then might have outdated copy in ipfs 
<img width="1178" alt="screen shot 2018-01-31 at 2 46 23 pm" src="https://user-images.githubusercontent.com/806312/35651742-9cb25cc4-0695-11e8-9c71-0751c7706223.png">

**Comment by schmidsi** [comment]
True. Thanks for reporting.
