### ISSUE TITLE
Fund trading history displays each trade ~92x

### ISSUE THREAD

**Issue by kingjacob** [melonproject/ipfs-frontend#219]
<img width="1205" alt="screen shot 2018-02-01 at 2 25 46 pm" src="https://user-images.githubusercontent.com/806312/35706780-f0da4c3c-075b-11e8-9719-3a3709191949.png">

**Comment by billymits** [comment]
I am having the same issue

**Comment by jennazenk** [comment]
opened issue in melon.js since the issue _might_ come from there : https://github.com/melonproject/melon.js/issues/175

**Comment by jennazenk** [comment]
Pushed a fix in melon.js, deployed here @melonproject/melon.js@0.6.42
