### ISSUE TITLE
"Create and deploy my fund"-Button isn't working

### ISSUE THREAD

**Issue by primius** [melonproject/ipfs-frontend#220]
When i'm clicking on "Create and deploy my fund" nothing happens.
I tried it with Firefox and Chrome (02.02.2018 00:19 MEZ).
The button even seems not to be clickable, or as if no action is assigned.

**Comment by udoncrypto** [comment]
me too

**Comment by TecateWine** [comment]
Same

**Comment by jennazenk** [comment]
Thanks for reporting - we're going to investigate this

**Comment by jennazenk** [comment]
I have this in the console when trying to setup a fund now : 

any idea @schmidsi @ferranbt  ?

<img width="709" alt="capture d ecran 2018-02-02 a 07 51 01" src="https://user-images.githubusercontent.com/17808182/35720396-de955ca0-07ed-11e8-97ae-b7acc17f732c.png">

**Comment by jennazenk** [comment]
connected to hosted node

**Comment by schmidsi** [comment]
@primius @udoncrypto @TecateWine Does the problem still exist? We deployed some fixes since friday. If yes, please feel free to reopen this issue.
