### ISSUE TITLE
Sometimes Melon Funds Ranking displays incorrect share price on first load.

### ISSUE THREAD

**Issue by kingjacob** [melonproject/ipfs-frontend#221]
The below is what first loads. It usually resolves on refresh.
<img width="1198" alt="screen shot 2018-02-02 at 4 27 03 pm" src="https://user-images.githubusercontent.com/806312/35760584-0b3b3e6c-0836-11e8-871d-efce5df562db.png">

**Comment by jennazenk** [comment]
This happens when cryptocompare delivers a wrong price for DOGE. It happens every now and then from what I've seen. Usually resolves as soon as next price is given.

**Comment by jennazenk** [comment]
thanks for reporting - we'll think on how we can avoid displaying the share price when the wrong price was given

**Comment by schmidsi** [comment]
We cannot do anything about this issue right now because prices come from the smart contract which is hard coded to cryptocompare which gives wrong number from time to time. Usually, at the least after 5 minutes prices are going back to normal.
