### ISSUE TITLE
Unable to get Kovan-Ether in order to start Test Fund

### ISSUE THREAD

**Issue by JulianBravis** [melonproject/ipfs-frontend#222]
Hi there, I want to start and register a melon fund and participate in the 2018 competition, but if I go to the faucet and request test tokens, I only get MLN-T and no ETH-T. I'm also getting "Transaction Error - Please try again". 

What could be the problem? Thanks for help.

**Comment by jennazenk** [comment]
Good catch @JulianBravis , the faucet was out of k-eth. I just replenished it so it should work now :)
