### ISSUE TITLE
Mixed content warning due to call to http://localhost:8545

### ISSUE THREAD

**Issue by zerr0ne** [melonproject/ipfs-frontend#224]
From main.bb7e7fdb.js I get the following warning:

```Mixed Content: The page at '<fund.page>' was loaded over HTTPS, but requested an insecure resource 'http://localhost:8545/'. This request has been blocked; the content must be served over HTTPS.```

I think the app should not be calling localhost in the first place, would be quite bad if you could set up something running on a local machine from your app =)...

**Comment by schmidsi** [comment]
We do this by purpose: We try to connect first to your local node and fall back to our hosted nodes if you don't run one or haven't the browser allowed to connect to it. I don't know of a method to check for this without running in this warning.

More info here: https://www.youtube.com/watch?v=Jb-9Xju6kMw&feature=youtu.be
