### ISSUE TITLE
Big disclaimer that live version is only temporary

### ISSUE THREAD

**Issue by schmidsi** [melonproject/ipfs-frontend#246]

**Comment by retotrinkler** [comment]
ideally something like

> AT THE END OF THE TESTING PERIOD OR AT ANY ARBITRARY POINT IN TIME AS DEFINED BY MELONPORT AG, THE SMART CONTRACT SYSTEM WILL BE CLOSED DOWN. THIS IS EXPECTED TO HAPPEN IN A MATTER OF DAYS OR WEEKS FROM DEPLOYMENT DATE. AT THIS POINT, THE USERS WON’T BE ABLE TO INTERACT WITH THE THE SMART CONTRACT SYSTEM ANYMORE THROUGH EXECUTING MAKE OR TAKE ORDERS, OR THROUGH THE INVEST FUNCTIONS.

similar to terms we used on https://ipfs.io/ipfs/QmZpeV44n5KzgXk9rYeHYX7QYovaTHyHgfAQ4PK5AkDr6c
