### ISSUE TITLE
In settings card add administrative functions

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/ipfs-frontend#25]
Initially should have those: 

- `Enable subscription in MLN` https://github.com/melonproject/protocol/blob/master/contracts/FundInterface.sol#L49 on-click `Refuse subscription in MLN`
- `Enable redemption in MLN` https://github.com/melonproject/protocol/blob/master/contracts/FundInterface.sol#L50 on-click `Refuse redemption in MLN`
- `Convert unclaimed rewards` https://github.com/melonproject/protocol/blob/master/contracts/FundInterface.sol#L61
- `Irreversibly shut down fund` https://github.com/melonproject/protocol/blob/master/contracts/FundInterface.sol#L61

**Comment by jennazenk** [comment]
Yep; need to implement them in melon.js first: https://github.com/melonproject/melon.js/issues/65

**Comment by jennazenk** [comment]
Fixed in styling branch
