### ISSUE TITLE
Cannot setup a fund

### ISSUE THREAD

**Issue by PvUtrix** [melonproject/ipfs-frontend#257]
I get the following error, when trying to submit a participation request, I tried different amounts, same results

e.g. 
https://kovan.etherscan.io/tx/0xedf660e4cc7f5e29cd6ebded0b842f6f2c116235ae4429a6d9b2b42be0701d24

Returned by the interface
```
Transaction error
Cannot encode token #0 [uint: undefined]. new BigNumber() not a number: undefined

```

My accounts
Your ethereum address: 0x4c6F6aAd2F75539C53c558dccb85A0f55568901F

Associated fund address: 0x2f95E6444826B9fe8bABBBd4ec19309E539E3b82

Screenshot 
https://yadi.sk/i/hKdxoyof3TEYfR

**Comment by jennazenk** [comment]
Could you try to generate a new wallet address, then create a new fund and try this one again please? Also can you confirms this happens right after creating a fund, when you're prompted to invest in your fund ?

**Comment by PvUtrix** [comment]
The previous screenshot didn't work for some reason, it's on this screen https://yadi.sk/i/4QGrW-df3TF2rg.
I'll try creating a new wallet and report

**Comment by PvUtrix** [comment]
Errors again https://yadi.sk/i/DYezQbVf3TF43T

**Comment by jennazenk** [comment]
hey @PvUtrix thansk for your input! Could you try again? It should work now :) Let me know

**Comment by schmidsi** [comment]
Closing this since it should work now
