### ISSUE TITLE
Clearer communicate if running on mainnet vs kovan

### ISSUE THREAD

**Issue by ShreyasChari** [melonproject/ipfs-frontend#261]
Hi,
I transferred a real ether to my address, which i now see, thanks for fixing. I don't see on the site anywhere about how this works. I tried to understand from your Medium.com video post but I don't even see the same things that are shown in the video. I have no idea what to do or how a portfolio works here. I also get no choices on buying any assets other than ETH and MLN. Isn't there a guide to any of this?

**Comment by schmidsi** [comment]
Hi, did you transfer real ether to the address of your account on melon.fund? Can you specify which address? Melon.fund runs on the Kovan test unless you run your own node. Do you run your own node?

**Comment by ShreyasChari** [comment]
Yes I transferred real ether.
On your website I didn't see any instructions at all and l presumed that's
what you need as it said insufficient ETH.
There's no explanation for anything and you're kinda left to figure it out
as you go.

**Comment by ShreyasChari** [comment]
This was the address that Melon portfolio said I should send Ether to...
0x07e964D026581c8D56fd5411e0D3Ab16C3fbcc1A

**Comment by schmidsi** [comment]
Ok I see. Here were the instructions: https://medium.com/melonport-blog/melon-manager-competitions-begin-b794aef54249

I checked your address and you sent indeed real Ether to an address on the test-net:
Mainnet: https://etherscan.io/address/0x07e964d026581c8d56fd5411e0d3ab16c3fbcc1a
Kovan: https://kovan.etherscan.io/address/0x07e964d026581c8d56fd5411e0d3ab16c3fbcc1a

Did you write down the mnemonic when you created the account on Kovan? I never tried but if you are lucky you might restore your wallet on the main-net with mycrypto.com.

I rename this issue in "Clearer communicate if running on mainnet vs kovan"

**Comment by ShreyasChari** [comment]
Please give me clear instructions on what to do next. I dont even know what
mycrypto.com is used for. I also did not know I needed metamask or needed
to be on a network. I am not a blockchain tech or anything but someone from
the investment management industry hence .
I do have the 12 word mnemonic. What do I do?

Thanks

**Comment by schmidsi** [comment]
@ShreyasChari please write me directly on simon@melonport.com
