### ISSUE TITLE
Deploy as a Parity Dapp

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/ipfs-frontend#36]
Ultra secure version by having d-portal w/in parity wallet https://github.com/paritytech/parity/wiki/Deploying-DApps-to-Parity-Wallet

Parity wallet uses content hash to github repo (and/or url) [mapping contract](https://github.com/paritytech/contracts/blob/master/GithubHint.sol)

Which means
- Content hosted on Github -> High availability
- Content checked against given contentHash -> High authenticity

**Comment by schmidsi** [comment]
Done
