### ISSUE TITLE
Refactor redux architecture according to ferranbt/frame with saga, etc.

### ISSUE THREAD

**Issue by schmidsi** [melonproject/ipfs-frontend#43]
After the first sprint and successful deploy, we need to refactor the architecture to a more clean and modular approach.

I suggest to follow @ferranbt's [architecture](https://github.com/ferranbt/frame) like here but with some requirements/questions to discuss here before.

- Modularisation: How can we isolate and possibly extract certain parts of the application for reusability. For example, the whole [web3-state management](https://github.com/melonproject/decentralized-portal/blob/c05f297c79d55999c57ded1eef1d874e1a69c636/src/components/web3/duck.js) could be extracted in it's own package and reused even outside of Melon.
- Plugability: It should be possible to simply replace a module with another and the other modules do not need to be updated (loose coupling, separation of concerns). For example: Replace the whole EVM-communication layer with a mocking module which speeds up development or for show-case purposes.

Happy to discuss more architectural thoughts in here.

**Comment by jennazenk** [comment]
Happy to discuss all of this and start moving to the new architecture after M-0
