### ISSUE TITLE
Add: Messages about wrong network; locked account etc

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/ipfs-frontend#46]

**Comment by schmidsi** [comment]
I already started on this in the [components/web3](https://github.com/melonproject/ipfs-frontend/tree/0.3/src/components/web3) folder. The idea is to have an onBlock callback (see web3/middleware.js) that updates the current web3 state. From there, it should be possible to read from the state if web3 is connected, which network, isSyncing, is-in sync (last block older than 20 seconds or so), ...

**Comment by jennazenk** [comment]
Fixed in previous deployment
