### ISSUE TITLE
Visitor mode

### ISSUE THREAD

**Issue by schmidsi** [melonproject/ipfs-frontend#54]
It should be possible to see everything of the frontend without having Metamask or anything installed.

Linked to #52

**Comment by noconstruct** [comment]
I have metamask and kovan running with a balance doesnt work at all melon.fund on ipfs

**Comment by jennazenk** [comment]
hello @noconstruct , would love to help you, can you give more precision on what is not working ? You can come over to our Gitter chat and we'll help you to get started!

**Comment by schmidsi** [comment]
https://github.com/melonproject/melon.js/issues/82
