### ISSUE TITLE
EnsureError : Insufficent MLN-T. Need 1.1 have: 0

### ISSUE THREAD

**Issue by shu-iro** [melonproject/ipfs-frontend#58]
Hi, I've just tried to make an initial investment on my melon fund but I get a promise error
`bundle.js:150288 0xf6ce74da0d6f59d80bb08681ff76903c1d1db806
ipfs.io/:1 Uncaught (in promise) EnsureError {name: "EnsureError", message: "Insufficent MLN-T. Need 1.1 have: 0", stack: "Error↵    at new EnsureError (https://ipfs.io/ipns…s/melon.fund/bundle.js:5069:13↵    at <anonymous>"}message: "Insufficent MLN-T. Need 1.1 have: 0"name: "EnsureError"stack: "Error↵    at new EnsureError (https://ipfs.io/ipns/melon.fund/bundle.js:16035:16)↵    at ensure (https://ipfs.io/ipns/melon.fund/bundle.js:16044:11)↵    at _callee$ (https://ipfs.io/ipns/melon.fund/bundle.js:149105:34)↵    at tryCatch (https://ipfs.io/ipns/melon.fund/bundle.js:59684:40)↵    at Generator.invoke [as _invoke] (https://ipfs.io/ipns/melon.fund/bundle.js:59922:22)↵    at Generator.prototype.(anonymous function) [as next] (https://ipfs.io/ipns/melon.fund/bundle.js:59736:21)↵    at step (https://ipfs.io/ipns/melon.fund/bundle.js:5058:30)↵    at https://ipfs.io/ipns/melon.fund/bundle.js:5069:13↵    at <anonymous>"__proto__: Error
Promise rejected (async)
(anonymous) @ bundle.js:150443
(anonymous) @ bundle.js:150390
onInvest @ bundle.js:184274
apply @ bundle.js:45604
baseInvoke @ bundle.js:153658
apply @ bundle.js:45605
(anonymous) @ bundle.js:71284
Button._this.handleClick @ bundle.js:73493
ReactErrorUtils.invokeGuardedCallback @ bundle.js:49261
executeDispatch @ bundle.js:49045
executeDispatchesInOrder @ bundle.js:49065
executeDispatchesAndRelease @ bundle.js:29387
executeDispatchesAndReleaseTopLevel @ bundle.js:29398
forEachAccumulated @ bundle.js:61614
processEventQueue @ bundle.js:29598
runEventQueueInBatch @ bundle.js:108042
handleTopLevel @ bundle.js:108052
handleTopLevelImpl @ bundle.js:111336
perform @ bundle.js:40445
batchedUpdates @ bundle.js:111253
batchedUpdates @ bundle.js:17869
dispatchEvent @ bundle.js:111411
`

Proof :
https://puu.sh/y7Fzf/709e1139fe.mp4

**Comment by jennazenk** [comment]
Hello, thank you for reporting that error. When you invest in your fund, you need 0.1 MLN more than the amount that you are trying to invest. The reason for this is that you need to pay the 0.1 MLN incentive for workers to execute your subscription request. So basically if you try to invest 2 MLN, make sure you have at least 2.1 MLN in your portfolio. Have a nice day!

**Comment by shu-iro** [comment]
Yes but may be add a toaster message or something like that to warn the lambda user.

**Comment by jennazenk** [comment]
Yes that's absolutely right, we are planning to :)
