### ISSUE TITLE
Display ranking of fund

### ISSUE THREAD

**Issue by jennazenk** [melonproject/ipfs-frontend#61]
(i) one dedicated page with ranking of all funds
(ii) on each fund's page display the ranking of the fund itself

**Comment by schmidsi** [comment]
Does it need to be a visualisation or is it sufficient to just display the rank?

I understand visualisation as some sort of infographic.

**Comment by jennazenk** [comment]
Only display ranking as before (will change title of issue)

**Comment by jennazenk** [comment]
Done
