### ISSUE TITLE
Stuck on "investing in your fund..."

### ISSUE THREAD

**Issue by vaivoda** [melonproject/ipfs-frontend#63]
I obtained k-ETH and k-MLN, created my fund successfully, but when I go to invest MLN I'm stuck on the "investing in your fund..." step.

I have no Metamask notification (which I think I'm supposed to get)

Here's the address: https://kovan.etherscan.io/address/0xe6054a228b6da740684aa4b2eeb9ea790834d48a

**Comment by schmidsi** [comment]
We had a problem with the pricefeed yesterday, so it may work now. That said, we have a problem with gas limit on Kovan, but that should only affect creating a fund, not investing in it.

Can you please check?
