### ISSUE TITLE
Twitter symbol next to shareprice

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/ipfs-frontend#65]
eg https://dev.twitter.com/web/tweet-button

with some prefilled text similar to:
_I know have a shareprice of .._
u prob will find a better text though :)

**Comment by schmidsi** [comment]
Attention: Only use the link, do not include Twitter JS API because it is a tracker.

**Comment by jennazenk** [comment]
closed here https://github.com/melonproject/ipfs-frontend/commit/4bd13a296a2673958a6437a16f456273ba902343
