### ISSUE TITLE
Taken to "Setup your fund" page upon refreshing fund interface.

### ISSUE THREAD

**Issue by lev-kusanagi** [melonproject/ipfs-frontend#75]
I set up a new fund, bought some shares, and exchanged Melon for Ether.

The transactions weren't reflected in the summary of holdings. After refreshing, I was taken to the "Setup your fund" and my preexisting fund was nowhere to be seen.

Using Metamask 3.12.1 and Google Chrome Version 62.0.3202.94

**Comment by jennazenk** [comment]
Should be fine since release 0.6
