### ISSUE TITLE
price of share 0

### ISSUE THREAD

**Issue by pier-rosini** [melonproject/ipfs-frontend#76]
The share price retrieved from the network is zero.
I haven't seen any error in the console and it's not easy to reproduce.

![bug](https://user-images.githubusercontent.com/11160921/33734951-2704220a-db8e-11e7-93b9-36044124992e.PNG)

**Comment by schmidsi** [comment]
Thanks for pointing to this. This happens when the price feed doesnt provide prices. We are currently migrating it to the new version which is underway. So stay tuned.

I leave this issue open as a reminder.

In the meantime, I check if we can bring the current price feed one up again.

**Comment by jennazenk** [comment]
Indeed pricefeed went down at some point yesterday. It is back; if you still see 0 for share price please let us know! @pier-rosini
