### ISSUE TITLE
Add a default loading indicator

### ISSUE THREAD

**Issue by schmidsi** [melonproject/ipfs-frontend#80]
On the first page load, it should have a spinner or something.

(A Melon Spinner?)

**Comment by schmidsi** [comment]
Will come in the modal #92

**Comment by peterdraw** [comment]
Try this one
![Uploading 01_Melon_spinner_1.gif…]()

**Comment by peterdraw** [comment]
![01_melon_spinner_1](https://user-images.githubusercontent.com/9424987/34708878-659666ae-f547-11e7-86d2-64df36c5b62b.gif)

**Comment by jennazenk** [comment]
Ahmad this looks gorgeous 😍

**Comment by schmidsi** [comment]
Awesome!

**Comment by jennazenk** [comment]
Fixed in 0.6
