### ISSUE TITLE
Small indicator of state of connection, account, ... on top right

### ISSUE THREAD

**Issue by schmidsi** [melonproject/ipfs-frontend#97]

**Comment by schmidsi** [comment]
ETH/MLN Balance, syncing, block overdue, ...

**Comment by schmidsi** [comment]
Connected peers (should be >3 @ferranbt ?)

**Comment by schmidsi** [comment]
Data valid

**Comment by jennazenk** [comment]
closed https://github.com/melonproject/ipfs-frontend/pull/133
